const CONSTANT_TYPES = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILED : 'FETCH_COLLECTIONS_FAILED',
    ADD_ITEMS_TO_CART : 'ADD_ITEMS_TO_CART',
    REMOVE_ITEMS_FROM_CART : 'REMOVE_ITEMS_FROM_CART',
    INCREASE_ITEM_TO_CART : 'INCREASE_ITEM_TO_CART',
    DECREASE_ITEM_FROM_CART : 'DECREASE_ITEM_FROM_CART',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILED : 'SIGN_IN_FAILED',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED : 'SIGN_OUT_FAILED',
    SIGN_OUT_START : 'SIGN_OUT_START',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION',
    CLEAN_CART_ITEMS : 'CLEAN_CART_ITEMS'
}

export default CONSTANT_TYPES;