const CONSTANT_TYPES = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILED : 'FETCH_COLLECTIONS_FAILED',
    ADD_ITEMS_TO_CART : 'ADD_ITEMS_TO_CART',
    REMOVE_ITEMS_FROM_CART : 'REMOVE_ITEMS_FROM_CART',
    INCREASE_ITEM_TO_CART : 'INCREASE_ITEM_TO_CART',
    DECREASE_ITEM_FROM_CART : 'DECREASE_ITEM_FROM_CART'
}

export default CONSTANT_TYPES;